#!/bin/bash

if [[ $TASK = 1 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=bottle --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64--data=bottle --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=cable --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=cable --type=good --epoch 30 &
elif [[ $TASK = 2 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=capsule --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=capsule --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=carpet --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=carpet --type=good --epoch 30 &
elif [[ $TASK = 3 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=grid --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=grid --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=hazelnut --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=hazelnut --type=good --epoch 30 &
elif [[ $TASK = 4 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=leather --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=leather --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=metal_nut --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=164 --data=metal_nut --type=good --epoch 30 &
elif [[ $TASK = 5 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=pill --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=pill --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=screw --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=screw --type=good --epoch 30 &
elif [[ $TASK = 6 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=tile --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=tile --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=toothbrush --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=toothbrush --type=good --epoch 30 &
elif [[ $TASK = 7 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=transistor --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=transistor --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=128 --data=wood --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --train_batch 32 --test_batch 16 --kmeans=64 --data=wood --type=good --epoch 30 &
elif [[ $TASK = 8 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --train_batch 32 --test_batch 64 --kmeans=128 --data=zipper --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --train_batch 32 --test_batch 64 --kmeans=64 --data=zipper --type=good --epoch 30 &
fi

wait
