#!/bin/bash

if [[ $TASK = 1 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --with_mask True --train_batch 16 --test_batch 32 --kmeans=128 --data=leather --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --with_mask True --train_batch 16 --test_batch 32 --kmeans=128 --data=carpet --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --with_mask True --train_batch 16 --test_batch 32 --kmeans=128 --data=grid --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --with_mask True --train_batch 16 --test_batch 32 --kmeans=128 --data=tile --type=good --epoch 30 &
elif [[ $TASK = 2 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --with_mask True --train_batch 16 --test_batch 32 --kmeans=128 --data=wood --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --with_mask False --train_batch 16 --test_batch 32 --kmeans=128 --data=leather --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=3 python model_weightSample.py --with_mask False --train_batch 16 --test_batch 32 --kmeans=128 --data=grid --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=2 python model_weightSample.py --with_mask False --train_batch 16 --test_batch 32 --kmeans=128 --data=carpet --type=good --epoch 30 &
elif [[ $TASK = 3 ]]; then
    CUDA_VISIBLE_DEVICES=0 python model_weightSample.py --with_mask False --train_batch 16 --test_batch 32 --kmeans=128 --data=tile --type=good --epoch 30 &
    CUDA_VISIBLE_DEVICES=1 python model_weightSample.py --with_mask False --train_batch 16 --test_batch 32 --kmeans=128 --data=wood --type=good --epoch 30 &
fi

wait
